### PR TITLE
update validation email and change subject line

### PR DESCRIPTION
**Pull request by zlavergne**

### CODE REVIEW

**Comment by zlavergne** [comment]
@taylorsmock need to push this review through quickly so we can push it out to prod. it's already been tested on staging and good to go. This is just minor content changes

**Comment by ghost** [comment]
Just out of curiosity, what was the problem with {task_link}?

**Review by ghost — APPROVED** [review]

**Comment by zlavergne** [comment]
@tsmock the link was adding the plain text of an anchor link (`<a ....` included) to the subject of the email. I figured the task id could suffice instead. I'm not sure if an email subject is able to have a link at all.

**Review by tsmock — APPROVED** [review]

**Comment by tsmock** [comment]
Fair enough. I thought it was just a link, not a html link. But just the task number makes more sense.

**Pull request merged**
